# Generated by Django 5.0.7 on 2024-08-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='doctor/default.jpg', upload_to='doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='slider/default.jpg', upload_to='slider')),
            ],
        ),
        migrations.RenameModel(
            old_name='EmergencyService',
            new_name='Features',
        ),
        migrations.RemoveField(
            model_name='about',
            name='features',
        ),
        migrations.RemoveField(
            model_name='clinictimetable',
            name='timetable',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.RemoveField(
            model_name='price',
            name='services',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='WorkingHour',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='subtitle',
            new_name='maintitle',
        ),
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='service/default.jpg', upload_to='service'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='about/default.jpg', upload_to='about'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='testimonial/default.jpg', upload_to='testimonial'),
        ),
        migrations.DeleteModel(
            name='AboutFeature',
        ),
        migrations.AddField(
            model_name='about',
            name='features',
            field=models.ManyToManyField(related_name='qualities', to='core.quality'),
        ),
        migrations.DeleteModel(
            name='ClinicTime',
        ),
        migrations.DeleteModel(
            name='ClinicTimetable',
        ),
        migrations.DeleteModel(
            name='PlanService',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
