# Generated by Django 5.0.7 on 2024-08-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorteam_quality_slider_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
    ]
