# Generated by Django 5.0.7 on 2024-08-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_features_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='buttontext',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
