# Generated by Django 5.0.7 on 2024-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feature_buttontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='service/defaultea.jpg', upload_to='service')),
                ('buttontext', models.CharField(max_length=200)),
            ],
        ),
    ]
