# Generated by Django 5.0.7 on 2024-08-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expertarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertarea',
            name='buttontext',
        ),
    ]
