# Generated by Django 5.0.7 on 2024-08-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessinfo_delete_expertarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='tab',
        ),
    ]
