# Generated by Django 5.0.7 on 2024-08-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_businessinfo_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='maintitle',
            field=models.CharField(default='Hello World', max_length=255),
        ),
    ]
