# Generated by Django 5.0.7 on 2024-08-08 08:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businessinfo_maintitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('author_image', models.ImageField(default='blog/profile/default.jpg', upload_to='blog/profile')),
                ('title', models.CharField(max_length=200)),
                ('blog_desc', models.TextField()),
                ('image', models.ImageField(default='blog/post/default.jpg', upload_to='blog/post')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default='about/defaultt.jpg', upload_to='about'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=100)),
                ('commenter_email', models.EmailField(max_length=254)),
                ('commenter_website', models.CharField(max_length=100)),
                ('comment_desc', models.CharField(max_length=300)),
                ('commenter_image', models.ImageField(default='blog/profile/default.jpg', upload_to='blog/profile')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blog')),
            ],
        ),
    ]
