# Generated by Django 5.0.7 on 2024-08-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blog_rename_image_about_image1_about_image2_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('buttontext', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logos/Logo.png', upload_to='logos/')),
                ('header_email', models.EmailField(max_length=254)),
                ('header_phone', models.CharField(max_length=20)),
                ('footer_content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='maintitle',
            field=models.CharField(max_length=255),
        ),
    ]
