# Generated by Django 5.0.7 on 2024-08-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
