# Generated by Django 5.0.7 on 2024-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='flaticon-electrocardiogram', max_length=200),
        ),
    ]
