# Generated by Django 5.0.7 on 2024-08-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_slider_buttontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='buttontext',
            field=models.CharField(max_length=200),
        ),
    ]
