# Generated by Django 5.0.7 on 2024-08-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_slider_buttontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='slider/banner.png', upload_to='slider'),
        ),
    ]
