# Generated by Django 5.0.7 on 2024-08-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_slider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='image',
            new_name='backgroundimage',
        ),
    ]
