# Generated by Django 5.0.7 on 2024-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_emergencyservice_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='google_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
