# Generated by Django 5.0.7 on 2024-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_subscription_sitecontent_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='company_address',
            field=models.CharField(default='Al Hulaila Industrial Zone-FZ RAK, UAE', max_length=150),
        ),
    ]
