# Generated by Django 5.0.7 on 2024-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_sitecontent_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BradcamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_bg', models.ImageField(default='bradcam_img/banner.png', upload_to='bradcam_img')),
                ('blog_bg', models.ImageField(default='bradcam_img/banner.png', upload_to='bradcam_img')),
                ('team_bg', models.ImageField(default='bradcam_img/banner.png', upload_to='bradcam_img')),
                ('contact_bg', models.ImageField(default='bradcam_img/banner.png', upload_to='bradcam_img')),
            ],
        ),
    ]
