# Generated by Django 5.0.7 on 2024-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_bradcamimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bradcamimage',
            name='about_bg',
            field=models.ImageField(default='bradcam_img/banner.png', upload_to='bradcam_img'),
        ),
    ]
