# Generated by Django 5.0.7 on 2024-08-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_bradcamimage_about_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='equipments',
            field=models.ManyToManyField(related_name='equipments', to='core.equipment'),
        ),
    ]
