# Generated by Django 5.0.7 on 2024-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_service_description_service_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, default='first', max_length=255),
        ),
    ]
