# Generated by Django 5.0.7 on 2024-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='introduction',
            field=models.TextField(),
        ),
    ]
