# Generated by Django 5.0.7 on 2024-08-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_equipment_category_alter_service_conclusion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
